global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['orchestrator:8000'] # Remplacez par l'adresse de votre application FastAPI
