from config import ServiceConfig


class ServiceRegistry:
    """Gestion centralisée des microservices"""
    def register(self, name: str, config: ServiceConfig): ...
    def discover(self, service_type: str): ...
    def health_check_all(self): ...